### ISSUE TITLE
Logged-in user can't change anything

### ISSUE THREAD

**Issue by soere** [cboulanger/bibliograph#198]
The directories toothed wheel does nothing - nearly. A small dot appears and vanishes when clicked. Like "I'd like to open a menu but there's nothing I can show you"

**Comment by soere** [comment]
Just for reference, fotos taken with old permissions:
![grafik](https://user-images.githubusercontent.com/46968019/52075729-47661680-258d-11e9-886a-91634db3a672.png)
Selected folder ist "Hauptordner" but any other will still do the same. Note that the + and - buttons are missing. 
By the way, it's the same with the shortList, no +/- and the spoke wheel there only allows to export. "Kopieren ..." is grey, and "moving" is missing. 
![grafik](https://user-images.githubusercontent.com/46968019/52076302-ae37ff80-258e-11e9-9eec-c26d4a89e773.png)

After relogin: your changes on the permissions did it.

**Comment by cboulanger** [comment]
Thank you. Given your initial permissions, what you saw is correct. The problem was that the datasource was assigned to you directly, not via a group, and this will give you only your "global" permissions for this datasource (which was 'user with read permissions'). To have more elevated access rights permissions, a group has to be used (or especially created for this purpose) in which the user gets assigned a role with these permissions.
